[project]
name = "voice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pvspeaker>=1.0.5",
    "pyaudio>=0.2.14",
    "requests>=2.32.5",
]
